### ISSUE TITLE
微信公众号没有出现底部菜单

### ISSUE THREAD

**Issue by latermonk** [SilenceHVK/wechatByNode#1]
你好

按照你的教程尝试了一下，发1 2 什么的都回复正常，但是就是公众号没有底部的菜单，请问这个是怎么回事儿？  谢谢。
[![pDg1UA.md.png](https://s1.ax1x.com/2018/01/17/pDg1UA.md.png)](https://imgchr.com/i/pDg1UA)

**Comment by SilenceHVK** [comment]
首先请确定你的微信公众号类型，教程中我有指明 订阅号 是不能通过 API 去自定义菜单的。如果你是直接down 的 github 上的源码运行的，建议你查看一下如下图代码：
![代码截图](http://img.blog.csdn.net/20180118092542252?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvaHZrQ29kZXI=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)
因为源码中为了测试消息加密功能，因此把 appid 已改为订阅号，为了避免错误所以给注释了，之后我会把注释去掉，感谢你的支持。

**Comment by wangzilong1997** [comment]
没有菜单部分的代码 感谢作者
